name: "git-branch-behind-main"
on:
  pull_request:
    branches:
      - master
jobs:
  git:
    name: Git master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check
        shell: bash
        run: |
          #!/usr/bin/env sh

          set -e

          if [ -n "$CI" ]; then
          SRC_ORIGIN="origin/"

          if [ -z "$GITHUB_BASE_REF" ]; then
          git remote set-branches origin '*'
          git fetch origin develop
          fi
          else
          SRC_ORIGIN=""
          fi

          DST_BRANCH=${GITHUB_BASE_REF:-"develop"}
          SRC_BRANCH=${GITHUB_HEAD_REF:-$(git branch --show-current)}

          if ! git merge-base --is-ancestor origin/${DST_BRANCH} ${SRC_ORIGIN}${SRC_BRANCH}; then
          echo "Not possible to fast-forward. Please, rebase the branch."
          exit 1;
          fi

          if [ $(git log --oneline --merges origin/${DST_BRANCH}..${SRC_ORIGIN}${SRC_BRANCH} | wc -l) -ne 0 ]; then
          echo "The source branch cannot contain merges. Please, rebase the branch."
          exit 1;
          fi

          yarn commitlint --from=origin/${DST_BRANCH}
